name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the Node.js version

      # Step 3: Install dependencies using npm ci
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the project (using the npm build script)
      - name: Build the project
        run: npm run build
